
Neos:
  Neos:
    fusion:
      autoInclude:
        Neos.NodeTypes.Navigation: true
    userInterface:
      translation:
        autoInclude:
          Neos.NodeTypes.Navigation:
            - 'NodeTypes/*'
